name: Deploy to VPS (Self-Hosted)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Local
    runs-on: self-hosted # Ini memerintahkan GitHub untuk menjalankan perintah di VPS-mu, bukan di server GitHub
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Sync files to Webroot
      run: |
        # Mengkopi file dari workspace Runner ke folder web server tujuan tanpa memaksa perubahan Owner/Group
        rsync -rltDzvO --delete \
          --exclude="/mobile-app/" \
          --exclude="/mobile-absensi/" \
          --exclude="/.git/" \
          --exclude="/.github/" \
          --exclude="webapp_ready.zip" \
          --exclude="*.sql" \
          ./ ${{ secrets.SERVER_TARGET_DIR }}
